### GET request to example server
GET http://localhost:8080/api/v1/file/heart.png

###
GET http://localhost:8080/api/v1/file/star.png

### POST uploading file
POST http://localhost:8080/api/v1/file/upload
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="file"; filename="star.png"
Content-Type: image/png

< ./files/star.png
--boundary--